---
apiVersion: v1
kind: Service
metadata:
  name: spring-application
  labels:
    app: spring-application
    version: "1.0.0"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-application
  labels:
    app: spring-application
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-application
  template:
    metadata:
      labels:
        app: spring-application
        version: "1.0.0"
    spec:
      containers:
        - name: spring-application
          image: "acrspring01.azurecr.io/spring-application:1.0.0"
          imagePullPolicy: Always
          envFrom:
            []
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "SPRING_APPLICATION_NAME"
              value: "spring-application"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "dev"
            - name: "spring.main.banner-mode"
              value: "off"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
          args: [ "" ]
          resources:
            {}
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Lima
