---
apiVersion: v1
kind: Service
metadata:
  name: spring-application
  labels:
    app: spring-application
    version: "1.0.1"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-application
  labels:
    app: spring-application
    version: "1.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-application
  template:
    metadata:
      labels:
        app: spring-application
        version: "1.0.1"
    spec:
      containers:
        - name: spring-application
          image: "acrspring01.azurecr.io/spring-application:1.0.1"
          imagePullPolicy: Always
          envFrom:
            []
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "SPRING_APPLICATION_NAME"
              value: "spring-application"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "dev"
            - name: "spring.main.banner-mode"
              value: "off"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
          args: [ "" ]
          resources:
            {}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: probe-type
                  value: startup
            failureThreshold: 3
            periodSeconds: 4
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: probe-type
                  value: liveness
            initialDelaySeconds: 3
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: probe-type
                  value: readiness
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Lima
