spring:
  cloud:
    config:
      label: master
  profiles:
    active: dev
  application:
    name: spring-application
  config:
    import: configserver:http://localhost:8888
springdoc:
  api-docs:
    path: /open-api/api-docs